Importar numpy

In [1]:
import numpy as np

Criar o array de vendas

In [2]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

print(pecas_vendidas)

[150 120  90 210 300 250 180]


Calcular o faturamento

In [3]:
faturamento = pecas_vendidas * 50

print(faturamento)

[ 7500  6000  4500 10500 15000 12500  9000]


Filtrar dias de pico

In [4]:
mascara = pecas_vendidas > 200

print(mascara)
print(pecas_vendidas[mascara])

[False False False  True  True  True False]
[210 300 250]


Criar a matriz

In [5]:
vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])

print(vendas)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


Total por loja com axis=1 (soma horizontal)

In [6]:
total_lojas = np.sum(vendas, axis=1)

print(total_lojas)

[  nan  680. 1230.]


A soma da Loja A resulta em nan porque existe uma falha no terceiro dia. Para calcular o total ignorando esse valor, use:

In [7]:
total_lojas = np.nansum(vendas, axis=1)

print(total_lojas)

[ 670.  680. 1230.]


Média diária geral ignorando NaN

In [8]:
media_rede = np.nanmean(vendas)

print(media_rede)

234.54545454545453


Verificar a meta diária

In [9]:
resultado_meta = np.where(
    vendas >= 200,
    'Meta Atingida',
    'Abaixo'
)

print(resultado_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


Gerar 50 categorias aleatórias

In [10]:
rng = np.random.default_rng(42)

categorias = np.array(['Eletrônicos', 'Roupas', 'Casa'])

vendas_categorias = rng.choice(categorias, size=50)

print(vendas_categorias)

['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


Contar vendas por departamento

In [11]:
departamentos, contagens = np.unique(
    vendas_categorias,
    return_counts=True
)

print(departamentos)
print(contagens)

['Casa' 'Eletrônicos' 'Roupas']
[21 12 17]


Encontrar a campanha campeã

In [12]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])

indice_campea = np.argmax(faturamento_campanhas)

print(indice_campea)
print(faturamento_campanhas[indice_campea])

3
89000


Organização e transformação de dados - Dias do mês

In [13]:
dias = np.arange(1, 31)

print(dias)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


Metas igualmente espaçadas

In [14]:
metas = np.linspace(20000, 30000, 5)

print(metas)

[20000. 22500. 25000. 27500. 30000.]


Converter decimais para inteiros

In [15]:
estoque = np.array([10.5, 20.1, 30.9])

estoque_inteiro = estoque.astype(int)

print(estoque_inteiro)

[10 20 30]


Últimos cinco dias em ordem invertida

In [16]:
ultimos_dias = dias[-5:][::-1]

print(ultimos_dias)

[30 29 28 27 26]


Redimensionamento e proteção de dados - Reshape de 12 meses

In [17]:
visitas = np.array([100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320])

visitas_trimestres = visitas.reshape(4, 3)

print(visitas_trimestres)

[[100 120 140]
 [160 180 200]
 [220 240 260]
 [280 300 320]]


Empilhar matrizes

In [18]:
primeiro_semestre = np.array([
    [100, 120, 140],
    [160, 180, 200]
])

segundo_semestre = np.array([
    [220, 240, 260],
    [280, 300, 320]
])

ano = np.vstack((primeiro_semestre, segundo_semestre))

print(ano)

[[100 120 140]
 [160 180 200]
 [220 240 260]
 [280 300 320]]


Copiar o primeiro trimestre

In [19]:
projecao = visitas_trimestres[0, :].copy()

projecao[0] = 999

print(projecao)
print(visitas_trimestres[0])

[999 120 140]
[100 120 140]


Achatar a matriz

In [20]:
visitas_1d = ano.ravel()

print(visitas_1d)

[100 120 140 160 180 200 220 240 260 280 300 320]


Ranking com argsort()

In [21]:
pontuacoes = np.array([85, 92, 78, 95, 88])

ranking = np.argsort(pontuacoes)

print(ranking)

[2 0 4 1 3]


ranking do maior para o menor:

In [22]:
ranking_desc = np.argsort(pontuacoes)[::-1]

print(ranking_desc)

[3 1 4 0 2]


Broadcasting com np.newaxis

In [23]:
precos = np.array([100, 200, 300])

precos_coluna = precos[:, np.newaxis]

print(precos_coluna)
print(precos_coluna.shape)

[[100]
 [200]
 [300]]
(3, 1)


aplicar três descontos simultaneamente:

In [24]:
descontos = np.array([0.10, 0.20, 0.30])

precos_com_descontos = precos_coluna * (1 - descontos)

print(precos_com_descontos)

[[ 90.  80.  70.]
 [180. 160. 140.]
 [270. 240. 210.]]


Resolver sistema de custos com np.linalg.solve()

In [25]:
A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([500, 100])

custos = np.linalg.solve(A, b)

print(custos)

[200. 100.]
